import mongoose from "mongoose";
import Product from "./models/product.model.js";
import Bundle from "./models/bundle.model.js";
import dotenv from "dotenv";

dotenv.config();

const sampleProducts = [
    // Vegetables
    {
        name: "Potato 500g",
        category: "Vegetables",
        price: 25,
        offerPrice: 20,
        image: ["potato_image_1.png", "potato_image_2.png", "potato_image_3.png", "potato_image_4.png"],
        description: ["Fresh and organic", "Rich in carbohydrates", "Ideal for curries and fries"],
        inStock: true,
    },
    {
        name: "Tomato 1 kg",
        category: "Vegetables",
        price: 40,
        offerPrice: 35,
        image: ["tomato_image.png"],
        description: ["Juicy and ripe", "Rich in Vitamin C", "Perfect for salads and sauces", "Farm fresh quality"],
        inStock: true,
    },
    {
        name: "Broccoli (500g)",
        category: "Vegetables",
        price: 60,
        offerPrice: 45,
        image: ["broccoli_new.jpg"],
        description: ["Nutrient-rich green broccoli", "High in fiber", "Perfect for steaming or stir-fry"],
        inStock: true,
    },
    {
        name: "Garlic (100g)",
        category: "Vegetables",
        price: 30,
        offerPrice: 25,
        image: ["garlic_new.jpg"],
        description: ["Powerful and aromatic garlic", "Essential cooking staple", "Known for health benefits"],
        inStock: true,
    },
    {
        name: "Ginger (200g)",
        category: "Vegetables",
        price: 40,
        offerPrice: 35,
        image: ["ginger_new.jpg"],
        description: ["Fresh and spicy ginger root", "Perfect for tea and cooking", "Natural digestive aid"],
        inStock: true,
    },
    {
        name: "Cucumber (1kg)",
        category: "Vegetables",
        price: 45,
        offerPrice: 38,
        image: ["cucumber_new.jpg"],
        description: ["Cool and hydrating cucumbers", "Perfect for salads and sandwiches", "Low in calories"],
        inStock: true,
    },
    {
        name: "Cauliflower (1 pc)",
        category: "Vegetables",
        price: 50,
        offerPrice: 42,
        image: ["cauliflower_new.jpg"],
        description: ["Fresh white cauliflower head", "Versatile and healthy", "Rich in vitamins"],
        inStock: true,
    },
    {
        name: "Green Chilli (100g)",
        category: "Vegetables",
        price: 15,
        offerPrice: 12,
        image: ["green_chilli_final.jpg"],
        description: ["Spicy green chillies", "Enhances flavor in every dish", "Farm fresh heat"],
        inStock: true,
    },
    {
        name: "Cabbage (1 pc)",
        category: "Vegetables",
        price: 35,
        offerPrice: 28,
        image: ["cabbage_new.jpg"],
        description: ["Crunchy green cabbage", "Ideal for coleslaw and stir-fries", "Packed with Vitamin K"],
        inStock: true,
    },
    {
        name: "Lady Finger (500g)",
        category: "Vegetables",
        price: 40,
        offerPrice: 32,
        image: ["lady_finger_new.jpg"],
        description: ["Fresh tender okra", "Rich in dietary fiber", "Classic family favorite"],
        inStock: true,
    },
    {
        name: "Brinjal (500g)",
        category: "Vegetables",
        price: 30,
        offerPrice: 24,
        image: ["brinjal_new.jpg"],
        description: ["Glossy purple brinjals", "Soft and meaty texture", "Perfect for roasting or curries"],
        inStock: true,
    },
    {
        name: "Carrot 500g",
        category: "Vegetables",
        price: 30,
        offerPrice: 28,
        image: ["carrot_image.png"],
        description: ["Sweet and crunchy", "Good for eyesight", "Ideal for juices and salads"],
        inStock: true,
    },
    {
        name: "Spinach 500g",
        category: "Vegetables",
        price: 18,
        offerPrice: 15,
        image: ["spinach_image_1.png"],
        description: ["Rich in iron", "High in vitamins", "Perfect for soups and salads"],
        inStock: true,
    },
    {
        name: "Onion 500g",
        category: "Vegetables",
        price: 22,
        offerPrice: 19,
        image: ["onion_image_1.png"],
        description: ["Fresh and pungent", "Perfect for cooking", "A kitchen staple"],
        inStock: true,
    },

    // Fruits
    {
        name: "Apple 1 kg",
        category: "Fruits",
        price: 120,
        offerPrice: 110,
        image: ["apple_image.png"],
        description: ["Crisp and juicy", "Rich in fiber", "Boosts immunity", "Perfect for snacking and desserts", "Organic and farm fresh"],
        inStock: true,
    },
    {
        name: "Orange 1 kg",
        category: "Fruits",
        price: 80,
        offerPrice: 75,
        image: ["orange_image.png"],
        description: ["Juicy and sweet", "Rich in Vitamin C", "Perfect for juices and salads"],
        inStock: true,
    },
    {
        name: "Banana 1 kg",
        category: "Fruits",
        price: 50,
        offerPrice: 45,
        image: ["banana_image_1.png"],
        description: ["Sweet and ripe", "High in potassium", "Great for smoothies and snacking"],
        inStock: true,
    },
    {
        name: "Mango 1 kg",
        category: "Fruits",
        price: 150,
        offerPrice: 140,
        image: ["mango_image_1.png"],
        description: ["Sweet and flavorful", "Perfect for smoothies and desserts", "Rich in Vitamin A"],
        inStock: true,
    },
    {
        name: "Grapes 500g",
        category: "Fruits",
        price: 70,
        offerPrice: 65,
        image: ["grapes_image_1.png"],
        description: ["Fresh and juicy", "Rich in antioxidants", "Perfect for snacking and fruit salads"],
        inStock: true,
    },

    // Dairy
    {
        name: "Amul Milk 1L",
        category: "Dairy",
        price: 60,
        offerPrice: 55,
        image: ["amul_milk_image.png"],
        description: ["Pure and fresh", "Rich in calcium", "Ideal for tea, coffee, and desserts", "Trusted brand quality"],
        inStock: true,
    },
    {
        name: "Paneer 200g",
        category: "Dairy",
        price: 90,
        offerPrice: 85,
        image: ["paneer_image.png"],
        description: ["Soft and fresh", "Rich in protein", "Ideal for curries and snacks"],
        inStock: true,
    },
    {
        name: "Eggs 12 pcs",
        category: "Dairy",
        price: 90,
        offerPrice: 85,
        image: ["eggs_image.png"],
        description: ["Farm fresh", "Rich in protein", "Ideal for breakfast and baking"],
        inStock: true,
    },
    {
        name: "Cheese 200g",
        category: "Dairy",
        price: 140,
        offerPrice: 130,
        image: ["cheese_image.png"],
        description: ["Creamy and delicious", "Perfect for pizzas and sandwiches", "Rich in calcium"],
        inStock: true,
    },
    {
        name: "GRB Ghee 2L",
        category: "Oil",
        price: 550,
        offerPrice: 480,
        image: ["ghee_grb.jpg"],
        description: ["Pure and aromatic GRB Ghee", "Sign of purity", "Traditional taste"],
        inStock: true,
    },
    {
        name: "Sunflower Oil 1L",
        category: "Oil",
        price: 180,
        offerPrice: 160,
        image: ["sunflower_oil.jpg"],
        description: ["Highly refined sunflower oil", "Rich in Vitamin E", "Low in saturated fats"],
        inStock: true,
    },
    {
        name: "Groundnut Oil 2L",
        category: "Oil",
        price: 450,
        offerPrice: 420,
        image: ["groundnut_oil.jpg"],
        description: ["Cold pressed groundnut oil", "Rich in antioxidants", "Natural flavor and aroma"],
        inStock: true,
    },
    {
        name: "Sesame Oil 1L",
        category: "Oil",
        price: 350,
        offerPrice: 320,
        image: ["sesame_oil.jpg"],
        description: ["Pure sesame oil", "Classic nutty flavor", "Ideal for traditional cooking"],
        inStock: true,
    },
    {
        name: "Coconut Oil (500ml)",
        category: "Oil",
        price: 250,
        offerPrice: 200,
        image: ["coconut_oil.jpg"],
        description: ["Pure and natural coconut oil", "Ideal for cooking and hair care", "Extracted from fresh coconuts"],
        inStock: true,
    },
    {
        name: "Dabur Mustard Oil (475ml)",
        category: "Oil",
        price: 180,
        offerPrice: 150,
        image: ["mustard_oil.jpg"],
        description: ["Authentic mustard oil flavor", "Perfect for traditional pickles and cooking", "Natural and pungent"],
        inStock: true,
    },
    {
        name: "Olive Pomace Oil (1L)",
        category: "Oil",
        price: 750,
        offerPrice: 600,
        image: ["olive_oil.jpg"],
        description: ["High-quality olive pomace oil", "Ideal for deep frying and sautéeing", "Mild flavor profile"],
        inStock: true,
    },
    {
        name: "Amul Cow Ghee (1L)",
        category: "Oil",
        price: 600,
        offerPrice: 550,
        image: ["amul_ghee.jpg"],
        description: ["Pure cow ghee from Amul", "Rich in aroma and taste", "Traditional Indian household staple"],
        inStock: true,
    },
    {
        name: "Fushi Organic Ghee (420g)",
        category: "Oil",
        price: 950,
        offerPrice: 800,
        image: ["fushi_ghee.jpg"],
        description: ["Premium grass-fed organic ghee", "Stone-pressed for purity", "Ideal for healthy cooking"],
        inStock: true,
    },
    {
        name: "Daily Fresh Curd 500g",
        category: "Dairy",
        price: 50,
        offerPrice: 45,
        image: ["curd_daily_fresh.jpg"],
        description: ["Fresh and creamy Daily Fresh Curd", "With Probiotics", "Family Pack quality"],
        inStock: true,
    },

    // Drinks
    {
        name: "Coca-Cola 1.5L",
        category: "Drinks",
        price: 80,
        offerPrice: 75,
        image: ["coca_cola_new.jpg"],
        description: ["Refreshing and fizzy", "Perfect for parties and gatherings", "Best served chilled"],
        inStock: true,
    },
    {
        name: "Pepsi 1.5L",
        category: "Drinks",
        price: 78,
        offerPrice: 73,
        image: ["pepsi_new.jpg"],
        description: ["Chilled and refreshing", "Perfect for celebrations", "Best served cold"],
        inStock: true,
    },
    {
        name: "Sprite 1.5L",
        category: "Drinks",
        price: 79,
        offerPrice: 74,
        image: ["sprite_new.jpg"],
        description: ["Refreshing citrus taste", "Perfect for hot days", "Best served chilled"],
        inStock: true,
    },
    {
        name: "Fanta 1.5L",
        category: "Drinks",
        price: 77,
        offerPrice: 72,
        image: ["fanta_new.jpg"],
        description: ["Sweet and fizzy", "Great for parties and gatherings", "Best served cold"],
        inStock: true,
    },
    {
        name: "7 Up 1.5L",
        category: "Drinks",
        price: 76,
        offerPrice: 71,
        image: ["7up_new.jpg"],
        description: ["Refreshing lemon-lime flavor", "Perfect for refreshing", "Best served cold"],
        inStock: true,
    },
    {
        name: "Frooti",
        category: "Drinks",
        price: 20,
        offerPrice: 18,
        image: ["frooti_new.jpg"],
        description: ["Mango drink", "Fresh and juicy", "Best served chilled"],
        inStock: true,
    },

    // Rice
    {
        name: "Ragi Flour 1kg", // Mapping to "Wheat Atta"
        category: "Rice",
        price: 250,
        offerPrice: 230,
        image: ["wheat_atta_new.jpg"],
        description: ["High-quality whole wheat", "Soft and fluffy rotis", "Rich in nutrients"],
        inStock: true,
    },
    {
        name: "Multigrain Atta 5kg",
        category: "Rice",
        price: 350,
        offerPrice: 320,
        image: ["multigrain_atta_new.jpg"],
        description: ["Goodness of 6 grains", "Rich in dietary fiber", "Soft and nutritious rotis"],
        inStock: true,
    },
    {
        name: "Basmati Rice 5kg",
        category: "Rice",
        price: 550,
        offerPrice: 520,
        image: ["basmati_rice_new.jpg"],
        description: ["Long grain and aromatic", "Perfect for biryani and pulao", "Premium quality"],
        inStock: true,
    },
    {
        name: "Brown Rice 5kg",
        category: "Rice",
        price: 300,
        offerPrice: 280,
        image: ["boiled_rice_new.jpg"],
        description: ["Healthier alternative to white rice", "Retains more nutrients", "Easy to digest"],
        inStock: true,
    },
    {
        name: "Maida 1kg",
        category: "Rice",
        price: 180,
        offerPrice: 160,
        image: ["brown_rice_new.jpg"],
        description: ["Whole grain rice", "High in fiber", "Natural nutty flavor"],
        inStock: true,
    },

    // Dal & Pulses
    {
        name: "Toor Dal",
        category: "Dal",
        price: 180,
        offerPrice: 160,
        image: ["toor_dal_new.jpg"],
        description: ["Premium quality Toor Dal", "Rich in protein", "Essential for daily meals"],
        inStock: true,
    },
    {
        name: "Moong Dal",
        category: "Dal",
        price: 150,
        offerPrice: 130,
        image: ["moong_dal_new.jpg"],
        description: ["Easy to digest Moong Dal", "Nutritious and healthy", "Perfect for khichdi"],
        inStock: true,
    },
    {
        name: "Masoor Dal",
        category: "Dal",
        price: 140,
        offerPrice: 120,
        image: ["masoor_dal_new.jpg"],
        description: ["Premium Masoor Dal", "Quick cooking", "Rich in iron"],
        inStock: true,
    },
    {
        name: "Green Gram",
        category: "Dal",
        price: 160,
        offerPrice: 140,
        image: ["green_gram_new.jpg"],
        description: ["Sproutable Green Gram", "Protein-rich", "Very nutritious"],
        inStock: true,
    },
    {
        name: "Black Chana",
        category: "Dal",
        price: 120,
        offerPrice: 100,
        image: ["black_chana_new.jpg"],
        description: ["Healthy Black Chana", "Powerhouse of nutrients", "Great for salads and curries"],
        inStock: true,
    },

    // Bakery
    {
        name: "Brown Bread 400g",
        category: "Bakery",
        price: 40,
        offerPrice: 35,
        image: ["brown_bread_image.png"],
        description: ["Soft and healthy", "Made from whole wheat", "Ideal for breakfast and sandwiches"],
        inStock: true,
    },
    {
        name: "Chocolate Cake 500g",
        category: "Bakery",
        price: 350,
        offerPrice: 325,
        image: ["chocolate_cake_image.png"],
        description: ["Rich and moist", "Made with premium cocoa", "Ideal for celebrations and parties"],
        inStock: true,
    },

    // Instant
    {
        name: "Maggi Noodles",
        category: "Instant",
        price: 55,
        offerPrice: 50,
        image: ["maggi_image.png"],
        description: ["Instant and easy to cook", "Delicious taste", "Popular among kids and adults"],
        inStock: true,
    },

    // Dry Fruits & Nuts
    {
        name: "Almonds",
        category: "DryFruits",
        price: 800,
        offerPrice: 750,
        image: ["almonds_new.jpg"],
        description: ["Premium California Almonds", "Rich in Vitamin E", "High in protein and fiber"],
        inStock: true,
    },
    {
        name: "Cashews",
        category: "DryFruits",
        price: 900,
        offerPrice: 850,
        image: ["cashews_new.jpg"],
        description: ["Large and crunchy Cashews", "Good source of magnesium", "Rich in healthy fats"],
        inStock: true,
    },
    {
        name: "Pistachios",
        category: "DryFruits",
        price: 1100,
        offerPrice: 1000,
        image: ["pistachios_new.jpg"],
        description: ["Roasted and salted Pistachios", "Packed with antioxidants", "Heart-healthy snack"],
        inStock: true,
    },
    {
        name: "Walnuts",
        category: "DryFruits",
        price: 1200,
        offerPrice: 1100,
        image: ["walnuts_new.jpg"],
        description: ["Premium Chilean Walnuts", "Brain-healthy food", "High in Omega-3"],
        inStock: true,
    },
    {
        name: "Pumpkin Seeds",
        category: "DryFruits",
        price: 500,
        offerPrice: 450,
        image: ["pumpkin_seeds_new.jpg"],
        description: ["Raw Pumpkin Seeds", "Rich in zinc", "Great for immunity"],
        inStock: true,
    },
    {
        name: "Sunflower Seeds",
        category: "DryFruits",
        price: 400,
        offerPrice: 350,
        image: ["sunflower_seeds_new.jpg"],
        description: ["Nutritious Sunflower Seeds", "Rich in Vitamin E", "Great for heart health"],
        inStock: true,
    },
    {
        name: "Raisins",
        category: "DryFruits",
        price: 300,
        offerPrice: 250,
        image: ["raisins_new.jpg"],
        description: ["Sweet and chewy Raisins", "Natural energy booster", "Rich in iron and fiber"],
        inStock: true,
    },

    // Cadbury Chocolates
    {
        name: "Cadbury Dairy Milk Crispello",
        category: "Chocolates & Sweets",
        price: 30,
        offerPrice: 25,
        image: ["cadbury_crispello.jpg"],
        description: ["Crunchy wafer dipped in chocolate", "Perfect for light snacking", "Crispy and creamy"],
        inStock: true,
    },
    {
        name: "Cadbury Bournville 70% Dark",
        category: "Chocolates & Sweets",
        price: 99,
        offerPrice: 90,
        image: ["cadbury_bournville_dark.jpg"],
        description: ["Rich cocoa from Ghana", "70% Dark Chocolate", "Intense and smooth taste"],
        inStock: true,
    },
    {
        name: "Cadbury Dairy Milk Silk Heart Blush",
        category: "Chocolates & Sweets",
        price: 150,
        offerPrice: 140,
        image: ["cadbury_silk_heart_blush.jpg"],
        description: ["Silk chocolate with a pop of heart", "Valentine special edition", "Smooth and creamy"],
        inStock: true,
    },
    {
        name: "Cadbury Dairy Milk Silk Oreo",
        category: "Chocolates & Sweets",
        price: 80,
        offerPrice: 75,
        image: ["cadbury_silk_oreo.jpg"],
        description: ["Silk chocolate with crunchy Oreo bits", "The best of both worlds", "Creamy and crunchy"],
        inStock: true,
    },
    {
        name: "Cadbury Fuse",
        category: "Chocolates & Sweets",
        price: 40,
        offerPrice: 35,
        image: ["cadbury_fuse.jpg"],
        description: ["Fusion of peanuts and caramel", "Chocolaty feast", "Crunchy and chewy"],
        inStock: true,
    },

    {
        name: "Dark Chocolate",
        category: "Chocolates & Sweets",
        price: 120,
        offerPrice: 100,
        image: ["dark_chocolate.jpg"],
        description: ["Rich and intense dark chocolate", "High cocoa content", "Perfect for baking or snacking"],
        inStock: true,
    },
    {
        name: "White Chocolate",
        category: "Chocolates & Sweets",
        price: 90,
        offerPrice: 80,
        image: ["white_chocolate.jpg"],
        description: ["Creamy and sweet white chocolate", "Smooth texture", "Ideal for desserts"],
        inStock: true,
    },
    {
        name: "Dairy Milk",
        category: "Chocolates & Sweets",
        price: 80,
        offerPrice: 70,
        image: ["dairy_milk.jpg"],
        description: ["Smooth and creamy milk chocolate", "Classic taste", "Perfect for gifting"],
        inStock: true,
    },
    {
        name: "KitKat",
        category: "Chocolates & Sweets",
        price: 50,
        offerPrice: 40,
        image: ["kitkat.jpg"],
        description: ["Crispy wafer fingers covered in milk chocolate", "Have a break, have a KitKat", "Perfect snack"],
        inStock: true,
    },
    {
        name: "Snickers",
        category: "Chocolates & Sweets",
        price: 45,
        offerPrice: 40,
        image: ["snickers.jpg"],
        description: ["Milk chocolate with peanuts and caramel", "Packed with peanuts", "Satisfies your hunger"],
        inStock: true,
    },
    {
        name: "Kinder Joy",
        category: "Chocolates & Sweets",
        price: 50,
        offerPrice: 45,
        image: ["kinder_joy.png"],
        description: ["Creamy treat with wafer balls and a surprise toy", "Loved by kids"],
        inStock: true,
    },
    {
        name: "Hard Candies",
        category: "Chocolates & Sweets",
        price: 40,
        offerPrice: 35,
        image: ["hard_candies.jpg"],
        description: ["Classic hard candy drops", "Assorted flavors", "Long-lasting sweetness"],
        inStock: true,
    },
    {
        name: "Lollipops",
        category: "Chocolates & Sweets",
        price: 60,
        offerPrice: 50,
        image: ["lollipops.jpg"],
        description: ["Fruity swirl lollipops", "Colorful and delicious", "Kids' favorite"],
        inStock: true,
    },
    {
        name: "Jelly Candies",
        category: "Chocolates & Sweets",
        price: 80,
        offerPrice: 70,
        image: ["jelly_candies.jpg"],
        description: ["Soft and chewy jelly hearts", "Fruity flavors", "Glazed with sugar"],
        inStock: true,
    },
    {
        name: "Caramel Toffees",
        category: "Chocolates & Sweets",
        price: 50,
        offerPrice: 45,
        image: ["caramel_toffees.jpg"],
        description: ["Rich and buttery caramel toffees", "Soft and chewy", "Melt-in-your-mouth goodness"],
        inStock: true,
    },
    {
        name: "Mysore Pak",
        category: "Chocolates & Sweets",
        price: 350,
        offerPrice: 320,
        image: ["mysore_pak.jpg"],
        description: ["Classic South Indian sweet made with ghee", "Rich and melt-in-the-mouth texture", "Authentic taste"],
        inStock: true,
    },
    {
        name: "Laddu",
        category: "Chocolates & Sweets",
        price: 300,
        offerPrice: 280,
        image: ["laddu.jpg"],
        description: ["Traditional Indian sweet balls", "Delicious and rich", "Perfect for celebrations"],
        inStock: true,
    },
    {
        name: "Gulab Jamun Mix",
        category: "Chocolates & Sweets",
        price: 150,
        offerPrice: 130,
        image: ["gulab_jamun_ready_mix.jpg"],
        description: ["Ready-to-make Gulab Jamun mix", "Soft and succulent jamuns in minutes", "Easy to prepare"],
        inStock: true,
    },
    {
        name: "Soan Papdi",
        category: "Chocolates & Sweets",
        price: 180,
        offerPrice: 160,
        image: ["soan_papdi.jpg"],
        description: ["Flaky and crunchy Soan Papdi", "Classic sweet treat", "Perfect for gifting"],
        inStock: true,
    },
    {
        name: "Payasam Mix",
        category: "Chocolates & Sweets",
        price: 120,
        offerPrice: 100,
        image: ["payasam_mix.jpg"],
        description: ["Traditional kheer/payasam mix", "Rich and creamy dessert", "Just add milk and cook"],
        inStock: true,
    },
    {
        name: "Sugar-Free Chocolates",
        category: "Chocolates & Sweets",
        price: 200,
        offerPrice: 180,
        image: ["sugar_free_chocolates.jpg"],
        description: ["Delicious chocolates with no added sugar", "Perfect for keto and low-carb diets", "Guilt-free indulgence"],
        inStock: true,
    },
    {
        name: "Dry Fruit Sweets",
        category: "Chocolates & Sweets",
        price: 550,
        offerPrice: 500,
        image: ["dry_fruit_sweets.jpg"],
        description: ["Premium sweets loaded with dry fruits", "Rich and nutritious", "Excellent for gifting"],
        inStock: true,
    },
    {
        name: "Protein Chocolates",
        category: "Chocolates & Sweets",
        price: 150,
        offerPrice: 130,
        image: ["protein_chocolates.jpg"],
        description: ["High-protein chocolate bars", "Fuel your workout", "Tastes like a treat, works like a supplement"],
        inStock: true,
    },
    {
        name: "Vegan Chocolates",
        category: "Chocolates & Sweets",
        price: 180,
        offerPrice: 160,
        image: ["vegan_chocolates.jpg"],
        description: ["Plant-based vegan chocolate bars", "Dairy-free and delicious", "Ethically sourced ingredients"],
        inStock: true,
    },
    {
        name: "Aggala",
        category: "Chocolates & Sweets",
        price: 150,
        offerPrice: 120,
        image: ["aggala.png"],
        description: ["Traditional roasted rice flour balls", "Sweetened with kithul jaggery", "Authentic Sri Lankan treat"],
        inStock: true,
    },
    {
        name: "Traditional Kavum",
        category: "Chocolates & Sweets",
        price: 200,
        offerPrice: 175,
        image: ["kavum.jpg"],
        description: ["Deep-fried sweet oil cakes", "Made with rice flour and treacle", "Crispy edges and soft center"],
        inStock: true,
    },
    {
        name: "Kokis",
        category: "Chocolates & Sweets",
        price: 120,
        offerPrice: 100,
        image: ["kokis.jpg"],
        description: ["Deep-fried crispy savory-sweet treat", "Flower-shaped traditional snack", "Classic festive favorite"],
        inStock: true,
    },
    {
        name: "Aluwa",
        category: "Chocolates & Sweets",
        price: 250,
        offerPrice: 220,
        image: ["aluwa.jpg"],
        description: ["Rice flour based sweet fudge", "Infused with cardamom and cashew nuts", "Melt-in-your-mouth texture"],
        inStock: true,
    },
    {
        name: "Bibikkan",
        category: "Chocolates & Sweets",
        price: 450,
        offerPrice: 400,
        image: ["bibikkan.jpg"],
        description: ["Traditional coconut cake", "Rich with spices, cashews, and dates", "Moist and flavorful"],
        inStock: true,
    },

    // Snacks
    {
        name: "Potato Chips (Classic)",
        category: "Snacks",
        price: 30,
        offerPrice: 28,
        image: ["lays_classic_new.jpg"],
        description: ["Classic salted potato chips", "Crispy and thin", "Perfect snack for any time"],
        inStock: true,
    },
    {
        name: "Potato Chips (Cream & Onion)",
        category: "Snacks",
        price: 30,
        offerPrice: 28,
        image: ["lays_cream_onion_new.jpg"],
        description: ["Sour cream and onion flavored chips", "Tangy and delicious", "All-time favorite"],
        inStock: true,
    },
    {
        name: "Potato Chips (Magic Masala)",
        category: "Snacks",
        price: 30,
        offerPrice: 28,
        image: ["lays_magic_masala_new.jpg"],
        description: ["Spicy and savory magic masala chips", "Indian style spice mix", "Bestseller"],
        inStock: true,
    },
    {
        name: "Mixture",
        category: "Snacks",
        price: 20,
        offerPrice: 18,
        image: ["kurkure_masala_munch_new.jpg"],
        description: ["Crunchy masala munch Kurkure", "Perfect tea-time snack", "Spicy and tangy"],
        inStock: true,
    },
    {
        name: "Murukku",
        category: "Snacks",
        price: 20,
        offerPrice: 18,
        image: ["kurkure_chilli_chatka_new.jpg"],
        description: ["Spicy chilli chatka Kurkure", "Extra spicy and crunchy", "Bold flavor"],
        inStock: true,
    },
    {
        name: "Bingo! Mad Angles (Achaari Masti)",
        category: "Snacks",
        price: 30,
        offerPrice: 28,
        image: ["bingo_mad_angles_achaari.jpg"],
        description: ["Tangy Achaari Masti flavored Bingo!", "Perfect triangle snack", "Bursting with Indian spices"],
        inStock: true,
    },
    {
        name: "Bingo! Yumitos (Cream & Onion)",
        category: "Snacks",
        price: 15,
        offerPrice: 10,
        image: ["bingo_yumitos_cream_onion.jpg"],
        description: ["Bingo! Yumitos Potato Chips", "Classic Cream & Onion flavor", "Crispy and light"],
        inStock: true,
    },
    {
        name: "Pringles BBQ",
        category: "Snacks",
        price: 120,
        offerPrice: 100,
        image: ["pringles_bbq_new.jpg"],
        description: ["Smokey BBQ flavored Pringles", "Unique stackable chips", "Perfect for sharing"],
        inStock: true,
    },
    {
        name: "Oreo Biscuits",
        category: "Snacks",
        price: 30,
        offerPrice: 25,
        image: ["oreo_box_new.jpg"],
        description: ["Rich cocoa biscuits with cream filling", "Classic milk's favorite cookie", "Perfect snack for kids"],
        inStock: true,
    },
    {
        name: "Sunfeast Dark Fantasy (Choco Fills)",
        category: "Snacks",
        price: 40,
        offerPrice: 30,
        image: ["dark_fantasy_choco_fills_new.jpg"],
        description: ["Luxury chocolate-filled biscuits", "Molten chocolate center", "Exquisite snack experience"],
        inStock: true,
    },
    {
        name: "Britannia Cake Gobbles (Fruity Fun)",
        category: "Snacks",
        price: 30,
        offerPrice: 25,
        image: ["britannia_cake_gobbles.jpg"],
        description: ["Delicious fruity flavored tea cake", "Fluffy and moist", "Perfect for tea-time"],
        inStock: true,
    },
    {
        name: "Britannia Cake Roll Yo! (Choco)",
        category: "Snacks",
        price: 20,
        offerPrice: 15,
        image: ["britannia_cake_roll_yo.jpg"],
        description: ["Choco Swiss Roll with cream centers", "Rich chocolate flavor", "Kids' favorite snack"],
        inStock: true,
    },

    // Household Care
    {
        name: "Surf Excel Detergent Powder 1kg",
        category: "Household Care",
        price: 150,
        offerPrice: 140,
        image: ["surf_excel_product.jpg"],
        description: ["Surf Excel Quick Wash detergent powder", "Tough stain removal with just one wash", "Keeps clothes looking like new"],
        inStock: true,
    },
];

const sampleBundles = [
    {
        name: "3 Days Vegetarian Kit",
        description: "Complete vegetarian goodness for 3 days. Includes varied fresh vegetables and paneer.",
        image: "veg_kit.png", // Ensure this image exists or use a placeholder/url
        price: 350, // Approximate discounted price
        items: [
            { productName: "Potato 500g", quantity: 2 },
            { productName: "Tomato 1 kg", quantity: 1 },
            { productName: "Onion 500g", quantity: 2 },
            { productName: "Paneer 200g", quantity: 2 },
            { productName: "Spinach 500g", quantity: 1 },
            { productName: "Carrot 500g", quantity: 1 },
            { productName: "Cabbage (1 pc)", quantity: 1 },
        ]
    },
    {
        name: "Bachelor Cooking Pack",
        description: "Survival kit for bachelors! Quick meals, eggs, and essentials.",
        image: "bachelor_pack.png",
        price: 450,
        items: [
            { productName: "Maggi Noodles", quantity: 5 },
            { productName: "Eggs 12 pcs", quantity: 1 },
            { productName: "Brown Bread 400g", quantity: 2 },
            { productName: "Amul Milk 1L", quantity: 2 },
            { productName: "Coca-Cola 1.5L", quantity: 1 },
            { productName: "Potato 500g", quantity: 1 },
            { productName: "Onion 500g", quantity: 1 },
        ]
    },
    {
        name: "Monthly Ration (2 People)",
        description: "Essential staples for 2 people for a month. Rice, flour, and veggies.",
        image: "monthly_ration.png",
        price: 2500,
        items: [
            { productName: "Basmati Rice 5kg", quantity: 2 },
            { productName: "Wheat Flour 5kg", quantity: 2 },
            { productName: "Potato 500g", quantity: 4 }, // 2kg
            { productName: "Onion 500g", quantity: 4 }, // 2kg
            { productName: "Tomato 1 kg", quantity: 2 },
            { productName: "Garlic (100g)", quantity: 2 },
            { productName: "Ginger (200g)", quantity: 1 },
            { productName: "Green Chilli (100g)", quantity: 2 },
        ]
    }
];

const seedDB = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log("Connected to MongoDB for seeding...");

        // Clear existing products and bundles
        console.log("Clearing existing products and bundles...");
        await Product.deleteMany({});
        await Bundle.deleteMany({});

        // Insert expanded sample products
        const insertedProducts = await Product.insertMany(sampleProducts);
        console.log(`Database seeded successfully with ${insertedProducts.length} products.`);

        const oilProducts = insertedProducts.filter(p => p.category === 'Oil');
        console.log(`Successfully seeded ${oilProducts.length} Oil products:`, oilProducts.map(p => p.name));

        // Insert sample bundles
        await Bundle.insertMany(sampleBundles);
        console.log(`Database seeded successfully with ${sampleBundles.length} bundles.`);

        process.exit(0);
    } catch (error) {
        console.error("Error seeding database:", error);
        process.exit(1);
    }
};

seedDB();
